services:
  frontend:
    build: ./frontend-react
    container_name: frontend-container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend-node
    container_name: backend-container
    ports:
      - "5000:5000"
    volumes:
      - ./backend-node:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DB_HOST=mysql  # Use service name as host
      - DB_PORT=3306
      - DB_USER=appuser  # New user instead of root
      - DB_PASSWORD=apppassword
      - DB_NAME=ftl
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ftl
      MYSQL_USER: appuser  # Add regular user
      MYSQL_PASSWORD: apppassword  # Add password for regular user
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend-node/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: